### ISSUE TITLE
Replication: Unable to create volume without "-o replicationGroup" parameter

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#269]
Create volume without replicationGroup parameter - 
root@cssosbe03-b14:~# docker volume create -d hpe --name=TEST-VOL -o size=19
Error response from daemon: create TEST-VOL: Invalid input received: %(reason)s
root@cssosbe03-b14:~# docker volume create -d hpe --name=TEST-VOL -o size=19 -o backend=3PAR
Error response from daemon: create TEST-VOL: Invalid input received: %(reason)s
root@cssosbe03-b14:~#

Create volume with replicationGroup parameter - 
root@cssosbe03-b14:~# docker volume create -d hpe --name=TEST-VOL -o replicationGroup=SHASHI
TEST-VOL
root@cssosbe03-b14:~# docker volume ls
DRIVER              VOLUME NAME
hpe:latest          SHASHI-VOL21
hpe:latest          TEST-VOL
root@cssosbe03-b14:~#

below is the hpe.conf contents
[DEFAULT]
# ssh key file required for driver ssh
# communication with array
ssh_hosts_key_file = /root/.ssh/known_hosts

# IP Address and port number of the etcd instance
# to use for storing volume meta data
# for setting up etcd client with cluster members give host_etcd_ip_address in this
# below format where each member's ip/port is given with comma as delimiter.
# For example, host_etcd_ip_address = 10.50.180.1:3379,10.50.164.1:3379,10.50.198.1:3379
# Please note this is only supported in managed plugin.
# Check the plugin version for the support.
host_etcd_ip_address = 192.168.68.44
host_etcd_port_number = 2379

# Client certificate and key details for secured etcd cluster
# Please note this is only supported in managed plugin.
# Check the plugin version for the support.
#host_etcd_client_cert = /root/plugin/certs/.pem
#host_etcd_client_key = /root/plugin/certs/.pem

# OSLO based Logging level for the plugin.
logging = DEBUG

# Enable 3PAR client debug messages
hpe3par_debug = True

# Suppress Requests Library SSL warnings
suppress_requests_ssl_warnings = True

# Plugin Driver Details. All drivers must
# specify an hpedockerplugin_driver location.
# All other attributes are driver specific,
# but are based directly on the OpenStack
# Cinder configuration details.
# DO NOT change the hpedockerplugin_driver for this sample file. It is already
# set to the correct value
hpedockerplugin_driver = hpedockerplugin.hpe.hpe_3par_fc.HPE3PARFCDriver

hpe3par_api_url = https://192.168.67.7:8080/api/v1
hpe3par_username = 3paradm
hpe3par_password = 3pardata
san_ip = 192.168.67.7
san_login = 3paradm
san_password = 3pardata
hpe3par_cpg = SHASHI-PRIM
hpe3par_snapcpg = SHASHI-PRIM-SNAP
# hpe3par_snapcpg is optional. If not provided, it defaults to hpe3par_cpg value
#hpe3par_iscsi_chap_enabled =
#hpe3par_iscsi_ips =
use_multipath = True
enforce_multipath = True
quorum_witness_ip = dummy_ip
backend_id = CSSOS-SSA04
replication_device = backend_id:CSSOS-SSA05,
                     replication_mode:synchronous,
                     cpg_map:SHASHI-PRIM:SHASHI-SEC,
                     snap_cpg_map:SHASHI-PRIM-SNAP:SHASHI-SEC-SNAP,
                     hpe3par_api_url:https://192.168.67.5:8080/api/v1,
                     hpe3par_username:3paradm,
                     hpe3par_password:3pardata,
                     san_ip:192.168.67.5,
                     san_login:3paradm,
                     san_password:3pardata

# "use_multipath" and "enforce_multipath" flags are mandatory for HPE 3PAR
# iSCSI volume plugin V2.0, and these flags should be set to True.
# These flags should be omitted for
# HPE 3PAR volume plugin v2.0.1 and later versions.
# Also, multiple IP addresses of iSCSI ports must be assigned to
# "hpe3par_iscsi_ips" parameter to configure multipath.

[3PAR]
ssh_hosts_key_file = /root/.ssh/known_hosts
logging = DEBUG
hpe3par_debug = True
suppress_requests_ssl_warnings = False
host_etcd_ip_address = 192.168.68.44
host_etcd_port_number = 2379
hpedockerplugin_driver = hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver
hpe3par_api_url = https://192.168.67.2:8080/api/v1
hpe3par_username = 3paradm
hpe3par_password = 3pardata
san_ip = 192.168.67.2
san_login=3paradm
san_password = 3pardata
hpe3par_cpg = SHASHI
hpe3par_snapcpg = SHASHI
hpe3par_iscsi_ips = 192.168.71.253
hpe3par_iscsi_chap_enabled = True
use_multipath = True
enforce_multipath = True
mount_conflict_delay = 30

[3PAR-MU3]
ssh_hosts_key_file = /root/.ssh/known_hosts
logging = DEBUG
hpe3par_debug = True
suppress_requests_ssl_warnings = False
host_etcd_ip_address = 192.168.80.1
host_etcd_port_number = 2379
hpedockerplugin_driver = hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver
hpe3par_api_url = https://15.212.192.252:8080/api/v1
hpe3par_username = 3paradm
hpe3par_password = 3pardata
san_ip = 15.212.192.252
san_login=3paradm
san_password = 3pardata
hpe3par_cpg = SHASHI
hpe3par_snapcpg = SHASHI-SNAP
hpe3par_iscsi_ips = 15.212.192.112
hpe3par_iscsi_chap_enabled = True
use_multipath = True
enforce_multipath = True
mount_conflict_delay = 30
root@cssosbe03-b14:~#

**Comment by imran-ansari** [comment]
@wdurairaj - This seems to be partly issue with the way replication implementation picks up the configuration parameters and partly how multi-backend support implementation populates the configuration.

To begin with, quorum_witness_ip field needs to be moved to "replication_device" dictionary field as it is only after "replication_device" is present, would the quorum_witness_ip made sense. 

And also, when multi-backend implementation parses the sections in hpe.conf, it should create a configuration object that contains all the possible fields (even those that are not present in hpe.conf but can be defined legally if needed). E.g. if in a backend section, if quorum_witness_ip is not defined, then also, the configuration object created by multi-backend implementation must have it with default value as None.

**Comment by wdurairaj** [comment]
This issue looks related to https://github.com/hpe-storage/python-hpedockerplugin/issues/254 where the ssh_key_hosts_file is looking into every backend.

**Comment by imran-ansari** [comment]
This got fixed in the pull request https://github.com/hpe-storage/python-hpedockerplugin/pull/286

**Comment by sonawane-shashikant** [comment]
If we don't specify any of the available parameters then volume created successfully. But we see error if we specify any parameter other than "replicationGroup".
Please see below console o/p

root@cssosbe03-b14 : ~ # docker volume create -d hpe --name shashivolume -o provisioning=thin
Error response from daemon: create shashivolume: Invalid input received: Request to create replicated volume cannot be fulfilled without specifying 'rcg_name' parameter in the request. Please specify 'rcg_name' and execute the request again.
root@cssosbe03-b14 : ~ # docker volume create -d hpe --name shashivolume
shashivolume
root@cssosbe03-b14 : ~ # docker volume ls
DRIVER              VOLUME NAME
hpe:latest          PP_Test_Vol02
hpe:latest          shashivol
hpe:latest          shashivolume
root@cssosbe03-b14 : ~ #

**Comment by imran-ansari** [comment]
root@cssosbe03-b14 : ~ # docker volume create -d hpe --name shashivolume -o provisioning=thin
The above command doesn't have the backend specified explicitly, In this case, DEFAULT backend is used.
The DEFAULT backend on the tester's blade has "replication_device" defined which makes it a replication configuration. For a replication configuration, specifying "replicationGroup" is mandatory. Since in the above command, tester has not specified "replicationGroup" so he is rightly getting the error message to specify "rcg_name".
If at all, the user needs to create a non-replicated volume, then he needs to configure a non-replicated backend and then use -o backend option. Alternately, he can remove "replication_device" from the DEFAULT section and then create volume using the above command.

**Comment by imran-ansari** [comment]
@sonawane-shashikant - could you please verify this?

**Comment by sandesh-desai** [comment]
Verified with the latest docker plugin on CentOS Linux release 7.5.1804 (Core)
Still facing the same issue that not able to create a volume without "-o replicationGroup"
Attaching the latest docker output and hpe.conf settings.

Test Bed:
Host:192.168.80.1  CentOS 
Host Version: CentOS Linux release 7.5.1804 (Core)


[docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2365873/docker.output.txt)
[hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2365874/hpe.conf.txt)

**Comment by imran-ansari** [comment]
Hi Sandesh, What you are seeing is expected behavior. Your default configuration is replication enabled using which you are trying to create regular non-replicated volume. Try using the other backend '3PAR' in your hpe.conf which is a non-replication configuration.

**Comment by sandesh-desai** [comment]
Let me check with other backend 3PAR in hpe.conf which is a non-replication configuration.

**Comment by sandesh-desai** [comment]
Working as per the  expected behavior.Please close this bug.

Attaching the output.

[docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2374810/docker.output.txt)
[hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2374811/hpe.conf.txt)

**Comment by sonawane-shashikant** [comment]
Closing as per above comment.
